### PR TITLE
More PSUL updates

### PR DESCRIPTION
**Pull request by Galithil**
several changes to how PSUL behaves to allow using either the db or the api

### CODE REVIEW

**Comment by senthil10** [comment]
@Galithil : Looks ok to me (from my very basic perspective), will merge it as it has been already 2 days and no one had any comments 👍

**Comment by Galithil** [comment]
It did not look _that_okay to me. Gimme a couple of hours more.

**Comment by senthil10** [comment]
Sure 😄 ✌️

**Comment by Galithil** [comment]
Okay, so it looks mostly fine. I'll keep an eye out for errors, but I got rid of all the ones I had.

**Comment by senthil10** [comment]
Awesome!!

**Pull request merged**
